"""Tests for iterative execution-feedback controller."""

import json
from dataclasses import dataclass

import pytest

from src.control.iterative_controller import run_iterative_feedback_loop


class _FakePromptResult:
    def __init__(self):
        self.prompt = "init"
        self.feedback_rounds = []

    def add_feedback_round(self, round_id, result_type, summary, details=None):
        self.feedback_rounds.append(
            {
                "round_id": round_id,
                "result_type": result_type,
                "summary": summary,
                "details": details or {},
            }
        )


@dataclass
class _FakeLLMResult:
    response_text: str
    raw_response: dict[str, str]


@dataclass
class _FakeRunResult:
    status: str
    report_json_path: str


@dataclass
class _FakeMutationRecord:
    generation_id: int
    source_round_id: int | None
    prompt_type: str
    prompt_path: str
    llm_output_path: str
    requested_mutant_count: int
    parsed_mutant_count: int
    fallback_used: bool
    mutation_score: float | None
    feedback_status: str | None
    reward_score: dict | None


def test_iterative_loop_switches_prompt_types_by_feedback(monkeypatch, tmp_path):
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    target_file = repo_root / "Target.java"
    target_file.write_text("public class Target {}\n", encoding="utf-8")

    statuses = [
        "coverage_command_failed",
        "test_execution_failed",
        "success",
    ]
    prompt_calls = []
    seen_conversations = []

    def fake_build_structured_prompt(_repo_root, _target_file, depth=10):
        assert depth == 6
        return _FakePromptResult()

    run_root = tmp_path / "iterative_runs" / "run_test"

    def fake_create_run_root():
        run_root.mkdir(parents=True, exist_ok=True)
        return str(run_root)

    def fake_build_targeted_prompt(prompt_result, prompt_type, report_or_path=None):
        del prompt_result
        prompt_calls.append((prompt_type, report_or_path))
        return f"prompt for {prompt_type}"

    def fake_call_llm_with_conversation(prompt_text, _config, conversation):
        seen_conversations.append(conversation)
        return _FakeLLMResult(
            response_text=f"// generated by: {prompt_text}",
            raw_response={"id": f"resp_{len(prompt_calls)}"},
        )
    def fake_create_llm_conversation(system_prompt=""):  # noqa: ARG001
        return {"previous_response_id": None, "system_prompt": system_prompt}

    def fake_generate_mutants(*args, **kwargs):
        generation_id = kwargs.get("generation_id", 1)
        source_round_id = kwargs.get("source_round_id")
        return [], _FakeMutationRecord(
            generation_id=generation_id,
            source_round_id=source_round_id,
            prompt_type="initialization" if source_round_id is None else "replenishment",
            prompt_path="/tmp/fake_mutation_prompt.txt",
            llm_output_path="/tmp/fake_mutation_output.txt",
            requested_mutant_count=kwargs.get("mutant_count", 0),
            parsed_mutant_count=0,
            fallback_used=False,
            mutation_score=None,
            feedback_status=None,
            reward_score=None,
        )


    class FakeRunner:
        def __init__(self, defects4j_bin, auto_clean=True):
            self.defects4j_bin = defects4j_bin
            self.auto_clean = auto_clean

        def run(self, llm_output_text, target_file, project_root):
            del llm_output_text, target_file, project_root
            idx = len(prompt_calls) - 1
            status = statuses[idx]
            report_path = repo_root / f"report_{idx + 1}.json"
            report_path.write_text(
                json.dumps({"status": status, "coverage_summary": {"line_coverage_percent": 10 + idx}}),
                encoding="utf-8",
            )
            return _FakeRunResult(status=status, report_json_path=str(report_path))

    monkeypatch.setattr("src.control.iterative_controller.build_structured_prompt", fake_build_structured_prompt)
    monkeypatch.setattr("src.control.iterative_controller._create_run_root", fake_create_run_root)
    monkeypatch.setattr("src.control.iterative_controller.build_targeted_prompt", fake_build_targeted_prompt)
    monkeypatch.setattr("src.control.iterative_controller.call_llm_with_conversation", fake_call_llm_with_conversation)
    monkeypatch.setattr("src.control.iterative_controller.create_llm_conversation", fake_create_llm_conversation)
    monkeypatch.setattr("src.control.iterative_controller._generate_mutants", fake_generate_mutants)
    monkeypatch.setattr("src.control.iterative_controller.Defects4jRunner", FakeRunner)

    result = run_iterative_feedback_loop(
        repo_root=str(repo_root),
        target_file=str(target_file),
        max_rounds=3,
        depth=6,
        defects4j_bin="/tmp/defects4j",
        auto_clean=False,
    )

    assert [item.prompt_type for item in result.rounds] == [
        "initialization",
        "compile-error",
        "runtime-error",
    ]
    assert [item.status for item in result.rounds] == statuses
    assert result.rounds_executed == 3
    assert result.final_status == "success"
    assert len({id(conv) for conv in seen_conversations}) == 1

    with open(result.summary_path, "r", encoding="utf-8") as file_obj:
        payload = json.load(file_obj)
    assert payload["rounds_executed"] == 3
    assert payload["rounds"][0]["prompt_type"] == "initialization"


def test_iterative_loop_rejects_non_positive_rounds(tmp_path):
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    target_file = repo_root / "Target.java"
    target_file.write_text("public class Target {}\n", encoding="utf-8")

    with pytest.raises(ValueError):
        run_iterative_feedback_loop(
            repo_root=str(repo_root),
            target_file=str(target_file),
            max_rounds=0,
        )


def test_iterative_loop_stops_early_on_full_line_coverage(monkeypatch, tmp_path):
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    target_file = repo_root / "Target.java"
    target_file.write_text("public class Target {}\n", encoding="utf-8")

    statuses = ["success", "success", "success"]
    line_coverages = [60.0, 100.0, 100.0]
    prompt_calls = []

    def fake_build_structured_prompt(_repo_root, _target_file, depth=10):
        del depth
        return _FakePromptResult()

    run_root = tmp_path / "iterative_runs" / "run_early_stop"

    def fake_create_run_root():
        run_root.mkdir(parents=True, exist_ok=True)
        return str(run_root)

    def fake_build_targeted_prompt(prompt_result, prompt_type, report_or_path=None):
        del prompt_result, report_or_path
        prompt_calls.append(prompt_type)
        return f"prompt for {prompt_type}"

    def fake_call_llm_with_conversation(prompt_text, _config, _conversation):
        return _FakeLLMResult(
            response_text=f"// generated by: {prompt_text}",
            raw_response={"id": f"resp_{len(prompt_calls)}"},
        )

    def fake_create_llm_conversation(system_prompt=""):  # noqa: ARG001
        return {"previous_response_id": None, "system_prompt": system_prompt}

    def fake_generate_mutants(*args, **kwargs):
        generation_id = kwargs.get("generation_id", 1)
        source_round_id = kwargs.get("source_round_id")
        return [], _FakeMutationRecord(
            generation_id=generation_id,
            source_round_id=source_round_id,
            prompt_type="initialization" if source_round_id is None else "replenishment",
            prompt_path="/tmp/fake_mutation_prompt.txt",
            llm_output_path="/tmp/fake_mutation_output.txt",
            requested_mutant_count=kwargs.get("mutant_count", 0),
            parsed_mutant_count=0,
            fallback_used=False,
            mutation_score=None,
            feedback_status=None,
            reward_score=None,
        )

    class FakeRunner:
        def __init__(self, defects4j_bin, auto_clean=True):
            self.defects4j_bin = defects4j_bin
            self.auto_clean = auto_clean

        def run(self, llm_output_text, target_file, project_root):
            del llm_output_text, target_file, project_root
            idx = len(prompt_calls) - 1
            report_path = repo_root / f"report_{idx + 1}.json"
            report_path.write_text(
                json.dumps(
                    {
                        "status": statuses[idx],
                        "coverage_summary": {"line_coverage_percent": line_coverages[idx]},
                    }
                ),
                encoding="utf-8",
            )
            return _FakeRunResult(status=statuses[idx], report_json_path=str(report_path))

    monkeypatch.setattr("src.control.iterative_controller.build_structured_prompt", fake_build_structured_prompt)
    monkeypatch.setattr("src.control.iterative_controller._create_run_root", fake_create_run_root)
    monkeypatch.setattr("src.control.iterative_controller.build_targeted_prompt", fake_build_targeted_prompt)
    monkeypatch.setattr("src.control.iterative_controller.call_llm_with_conversation", fake_call_llm_with_conversation)
    monkeypatch.setattr("src.control.iterative_controller.create_llm_conversation", fake_create_llm_conversation)
    monkeypatch.setattr("src.control.iterative_controller._generate_mutants", fake_generate_mutants)
    monkeypatch.setattr("src.control.iterative_controller.Defects4jRunner", FakeRunner)

    result = run_iterative_feedback_loop(
        repo_root=str(repo_root),
        target_file=str(target_file),
        max_rounds=5,
        defects4j_bin="/tmp/defects4j",
        auto_clean=False,
    )

    assert result.rounds_executed == 2
    assert [item.status for item in result.rounds] == ["success", "success"]
    assert result.final_status == "success"
